# Use an official Python image as a base
FROM python:3.12

# Set the working directory inside the container
WORKDIR /rag

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    tesseract-ocr \
    libtesseract-dev \
    poppler-utils \
    libxml2-dev \
    libxslt1-dev \
    antiword \
    unrtf \
    flac \
    ffmpeg \
    lame \
    libmad0 \
    libsox-fmt-mp3 \
    sox \
    libjpeg-dev \
    swig \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install Python dependencies
RUN pip install --upgrade -r requirements.txt

# Copy the application code into the container
COPY . .

# Set environment variables
#ENV GOOGLE_API_KEY=<Your_Google_API_Key>

# Command to run your application
CMD ["python", "rag.py"]