# Use an official Node.js image as the base
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY ./package.json ./
#COPY ./package-lock.json ./
COPY ./pnpm-lock.yaml ./

RUN npm install mongodb
RUN npm install express
RUN npm install axios
RUN npm install cors



# Install dependencies using pnpm
RUN npm install -g pnpm && pnpm install 

# Copy the rest of the application code
COPY . .

# Expose the port the app will run on
EXPOSE 3000

# Start the application
CMD ["pnpm", "dev"]